### ISSUE TITLE
Setup complete but cannot get project running as per README

### ISSUE THREAD

**Issue by johnpaulhayes** [GoTeamEpsilon/ctakes-rest-service#36]
Hi Folks, 

I'm super happy that this is an open source project and thank you so much for starting it! 

However, Im stuck. 
I've installed (no errors!) on a Ubuntu (Xenial) server in AWS however, we're at a loss regarding the next steps as the README is not clear yet. 

We've the system up and running (docker-compose start) and can see that the webserver is listening on 8080 (verified by telnet)

Hoever, when we send a POST as per the documentation -- nothing happens. 

Any help would be greatly appreciated as I'd love to get this up and running and contribute back to the project. 

Thanks in advance! 
JP

**Comment by tjaffri** [comment]
Same here... the following returns nothing: curl -d "data=hello world" -X POST http://localhost:8080/ctakes-nlp-service/ctakesnlp/analyze

Any ideas?

**Comment by tjaffri** [comment]
@MatthewVi you offered to help somebody get this working in issue #34 comments. I am based in Seattle and happy to jump on a call with you if the offer for help offers to this issue as well? I can commit to updating the README with instructions that others can benefit from (I have PC, Mac and Linux environments set up). Please let me know if you can spare an hour... I promise the resulting README updates will be well worth the time since it looks like a few others are interested in this as well. Thanks!

**Comment by MatthewVi** [comment]
Hi @johnpaulhayes and @tjaffri - please see https://github.com/GoTeamEpsilon/ctakes-rest-service/pull/37#issuecomment-422989086

**Comment by tjaffri** [comment]
Awesome, thanks so much @MatthewVi! I stepped away from this for a bit since I ran into issues, but will look at it again. Are there any specific contributions you are interested in? To begin with I'll report any issues I have following the updated README and suggest edits. Amazing work, much appreciated!

**Comment by MatthewVi** [comment]
@tjaffri Awesome. For the time being, I'm thinking just having your notes on how the install goes would be great!

**Comment by tjaffri** [comment]
@johnpaulhayes I propose we can close this. See PR #51 which I have verified gets the project up and running on Ubuntu (in AWS, like you).

**Comment by MatthewVita** [comment]
Hi. One of the Team Epsilon folks here. I have been away from open source for many months due to health issues.

You may be interested in reviewing the brand new README, which may lead you to a smoother install. Please let me know if you have any difficulties navigating it.
