### ISSUE TITLE
Does folder "sno_rx_16ab_db" contain all load scripts?

### ISSUE THREAD

**Issue by chnlyi** [GoTeamEpsilon/ctakes-rest-service#49]
I successfully installed service. However, my MySQL loading was fast and I didn't get any meaningful results.

**Comment by subuiyer411** [comment]
@chnlyi Do check if the data got inserted into the tables in MySQL.

**Comment by adminflexprn** [comment]
What's the best way to keep this database upto date? Is there a master file that can be used to update this DB periodically?

**Comment by MatthewVita** [comment]
Hi. One of the Team Epsilon folks here. I have been away from open source for many months due to health issues.

The scripts include the typical cTAKES resources as called out in the official setup guide. There have been adjustments to the README so that the scripts aren't run in a loop - this caused issues for some users because it would halt operation for password re-entry here and there. Sometimes it would halt an operation in general.

Also, you may be interested in reviewing the brand new README, which may lead you to a smoother install. Please let me know if you have any difficulties navigating it.
