### ISSUE TITLE
Figure out how to run with LetsEncrypt

### ISSUE THREAD

**Issue by MatthewVi** [GoTeamEpsilon/ctakes-rest-service#9]

**Comment by danora24** [comment]
1a. Using SSL is a combo of making the right cert AND ALSO setting the proper settings on your webserver to make the SSL work right, so will also be contributing Tomcat Java guidelines.
2. Ivan Ristic is the main guy in the world on documenting / improving SSL. He wrote this short / free [OpenSSL guidebook](https://www.feistyduck.com/books/openssl-cookbook/) that he's updated constantly since 2018. It will be the main guide for all this.
